step0 = {'id': '0', 'name': 'Ankieta dotycząca opinii na temat rozwoju systemów e-zdrowia w Polsce.', 
 'questions': [
     {'number': 1, 
      'text': "<p class='right'>Kraków, 11.04.2011</p></br><p>Szanowni Państwo</p></br><p>Rozwój systemów e‑zdrowia budzi duże zainteresowania ze względu na potencjalne korzyści dotyczące jakości i dostępności usług medycznych oraz ich efektywności kosztowej. W ramach programu badawczego realizowanego w Instytucie Zdrowia Publicznego chcemy określić możliwości rozwoju systemów e‑zdrowia w warunkach polskiej ochrony zdrowia. Istotnym elementem tego badania jest analiza akceptacji aplikacji e‑zdrowia przez uczestników rynku usług zdrowotnych, zarówno po stronie świadczeniobiorców jak i świadczeniodawców. </p><p>Zwracam się do Państwa z prośbą o udział w badaniu ankietowym, które ma przybliżyć opinie na temat sfery e‑zdrowia wśród osób zaangażowanych w zarządzanie placówkami medycznymi w Polsce.</p><p>Ankieta jest dostępna na stronie internetowej www.swop.med.pl. Zawiera ok. 30 pytań zawierających opcje wyboru, tak więc całkowity czas potrzebny do odpowiedzi na pytania nie powinien przekroczyć 15-20 minut.</p><p>Po wpisaniu tego adresu w przeglądarce  internetowej pojawi się pytanie o numer identyfikacyjny. Bardzo proszę wpisać tam nr ……. Wyniki ankiet są analizowane w sposób anonimowy, a identyfikator służy ograniczeniu nieuprawnionych wpisów oraz udostępnieniu formularza ankiety właściwego dla odpowiedniej grupy respondentów.</p><p>Doskonale rozumiemy presje czasową związaną z Państwa stanowiskiem, dlatego tym bardziej doceniamy udział w badaniu. Dziękujemy za czas poświęcony na jej wypełnienie.</p><p>Z wyrazami szacunku</p><p class='padded'>dr med. Mariusz Duplaga<br>Koordynator badania<br>Zakład Informacji Naukowej<br>Instytut Zdrowia Publicznegonego UJCM</p>"}]
}

step1 = {'id': '1', 'name': 'Ankieta dotycząca opinii na temat rozwoju systemów e-zdrowia w Polsce.', 
 'questions': [
     {'number': 1, 
      'text': 'Systemy informatyczne mają podstawowe znaczenie dla sprawnego zarządzania placówką ochrony zdrowia', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
     {'number': 2, 
      'text': 'Wykorzystanie systemów informatycznych w realizacji świadczeń medycznych jest niewystarczające:', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
     {'number': 3, 
      'text': 'Lekarz i inni pracownicy ochrony zdrowia powinni korzystać w większym stopniu z systemów informatycznych w trakcie świadczenia usług medycznych', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
     {'number': 4, 
      'text': 'Przez pojęcie e‑zdrowia rozumie się zwykle różnorodne zastosowania technologii komputerowych i telekomunikacyjnych dla realizacji zadań związanych z ochroną zdrowia i medycyną. Czy uważa Pan/i, że systemy e-zdrowia mają istotne znaczenie dla nowoczesnej ochrony zdrowia', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
     {'number': 5, 
      'text': 'Uważam, że w Polsce na razie nie ma miejsca dla systemów telemedycznych i e-zdrowia', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
     {'number': 6, 
      'text': 'Rozwój systemów e‑zdrowia sprawdza się tylko w krajach najbogatszych ', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecdowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie '},
         {'number': 5, 'text': 'zdecydowanie nie'}]}
]} 

step2 = {'id': '2', 'name': ' ', 
 'questions': [
     {'number': 1, 
      'text': 'Inicjatywa w zakresie rozwoju systemów e-zdrowia powinna pochodzić od:', 
      'helptext': 'pacjentów i ich rodzin', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 2,
       'helptext': 'lekarzy', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 3, 
       'helptext': 'pięlegniarek', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 4, 
       'helptext': 'specjalistów zdrowia publicznego', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 5, 
       'helptext': 'kadry zarządzającej placówek medycznych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 6, 
       'helptext': 'specjalistów IT placówek medycznych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 7, 
       'helptext': 'Ministerstwa Zdrowia', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 8, 
       'helptext': 'NFZ', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'w znacznym stopniu'},
         {'number': 2, 'text': 'w umiarkowanym stopniu'},
         {'number': 3, 'text': 'w niewielkim stopniu'},
         {'number': 4, 'text': 'w żadnum stopniu '},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
]} 

step3 = {'id': '3', 'name': ' ', 
 'questions': [
     {'number': 1, 
      'text': '8. Korzyści z rozwoju systemów e-zdrowia dla poszczególnych grup lub instytucji wymienionych poniżej są: ', 
      'helptext': 'pacjentów i ich rodzin', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 2, 
       'helptext': 'lekarzy', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 3, 
       'helptext': 'pięlegniarek', 
       'type': 'select', 'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 4, 
       'helptext': 'specjalistów zdrowia publicznego', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 5, 
       'helptext': 'kadry zarządzającej placówek medycznych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 6, 
       'helptext': 'specjalistów IT placówek medycznych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 7, 
       'helptext': 'Ministerstwa Zdrowia', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
      {'number': 8, 
       'helptext': 'NFZ', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'bardzo duże'},
         {'number': 2, 'text': 'duże'},
         {'number': 3, 'text': 'umiarkowane'},
         {'number': 4, 'text': 'brak korzyści'},
         {'number': 5, 'text': 'trudno powiedzieć'}]},
]} 

step4 = {'id': '4', 'name': ' ', 
 'questions': [
     {'number': 1, 
      'text': '9. Przesłanką dla wdrażania systemów e‑zdrowia powinno być:', 
      'helptext': 'a. usprawnienie zarządzania placówkami ochrony zdrowia ', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 2, 
       'helptext': 'b. ograniczenie wydatków na świadczenia medyczne', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 3, 
       'helptext': 'c. poprawa jakości opieki', 
       'type': 'select', 'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 4, 
       'helptext': 'd. większa dostępność usług', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 5, 
       'helptext': 'e. poprawa jakości życia pacjenta', 
       'type': 'select', 
       'options': [
       {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 6, 
       'helptext': 'f. poprawa bezpieczeństwa pacjenta', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 7, 
       'helptext': 'g. skuteczniejsze monitorowanie zjawisk epidemiologicznych', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 8, 
       'helptext': 'h. realizacja interwencji z zakresu zdrowia publicznego', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 9, 
       'helptext': 'i. szerzenie świadomości zdrowotnej', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 10, 
       'helptext': 'j. usprawnienie komunikacji pomiędzy lekarzem i pacjentem', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 11, 
       'helptext': 'k. usprawnienie komunikacji pomiędzy świadczeniodawcami', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
]} 

step5 = {'id': '5', 'name': ' ', 
 'questions': [
     {'number': 1, 
      'text': '10. Jakie są według Pana/i główne ograniczenia rozwoju i implementacji systemów telemedycznych i e‑zdrowia w Polsce? ', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 2, 
       'helptext': 'b. brak infrastruktury technicznej', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 3, 
       'helptext': 'c. brak środków finansowych', 
       'type': 'select', 'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 4, 
       'helptext': 'd. niechęć lekarzy', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 5, 
       'helptext': 'e. brak akceptacji ze strony pacjentów', 
       'type': 'select', 
       'options': [
       {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 6, 
       'helptext': 'f. ograniczona umiejętność posługiwania się technologiami informatycznymi wśród pracowników ochrony zdrowia', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 7, 
       'helptext': 'g. ograniczone umiejętności posługiwania się technologiami informatycznymi w społeczeństwie', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 8, 
       'helptext': 'h. brak sprawdzonego modelu biznesowego', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 9, 
       'helptext': 'i. brak finansowania tego typu usług przez NFZ', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
      {'number': 10, 
       'helptext': 'j. niedostępność sprawdzonych rozwiązań ', 
       'type': 'select', 
       'options': [
        {'number': 1, 'text': 'zdecydowanie tak'},
         {'number': 2, 'text': 'raczej tak'},
         {'number': 3, 'text': 'trudno powiedzieć'},
         {'number': 4, 'text': 'raczej nie'},
         {'number': 5, 'text': 'zdecydowanie nie'}]},
]} 

step6 = {'id': '6', 'name': ' ', 
 'questions': [
      {'number': 1, 
      'text': 'Czy w placówce medycznej, którą Pan/i zarządza lub pracuje wykorzystywane są systemy telemedyczne i e‑zdrowia:', 
      'helptext': 'a. portal/strona internetowa placówki', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 2, 
       'helptext': 'b. zintegrowany szpitalny system informacyjny', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 3, 
       'helptext': 'c. system informatyczny dla potrzeb gabinetu lekarskiego ', 
       'type': 'select', 'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 4, 
       'helptext': 'd. elektroniczna dokumentacja pacjenta', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 5, 
       'helptext': 'e. internetowy dostęp do dokumentacji medycznej dla pacjenta', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 6, 
       'helptext': 'f. internetowa rejestracja na wizyty w poradni', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 7, 
       'helptext': 'g. radiologiczny system informacyjny', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 8, 
       'helptext': 'h. teleradiologia', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 9, 
       'helptext': 'i. telekonsultacje dla pacjentów', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 10, 
       'helptext': 'j. telekonsultacje z innymi placówkami medycznymi', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
       {'number': 11, 
       'helptext': 'k. system monitorowania dla pacjentów z chorobami przewlekłymi', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},
      {'number': 12, 
       'helptext': 'l. system teleopieki w warunkach domowych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak'},
         {'number': 2, 'text': 'nie'}]},     
]} 

step7 = {'id': '7', 'name': ' ', 
 'questions': [
      {'number': 1, 
      'text': 'Czy w placówce medycznej, którą Pan/i zarządza lub pracuje wykorzystywane są systemy telemedyczne i e‑zdrowia:', 
      'helptext': 'a. portal/strona internetowa placówki', 
      'type': 'select', 
      'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 2, 
       'helptext': 'b. zintegrowany szpitalny system informacyjny', 
       'type': 'select', 
      'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 3, 
       'helptext': 'c. system informatyczny dla potrzeb gabinetu lekarskiego ', 
       'type': 'select', 
      'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 4, 
       'helptext': 'd. elektroniczna dokumentacja pacjenta', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 5, 
       'helptext': 'e. internetowy dostęp do dokumentacji medycznej dla pacjenta', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 6, 
       'helptext': 'f. internetowa rejestracja na wizyty w poradni', 
       'type': 'select', 
        'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 7, 
       'helptext': 'g. radiologiczny system informacyjny', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 8, 
       'helptext': 'h. teleradiologia', 
       'type': 'select', 
        'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 9, 
       'helptext': 'i. telekonsultacje dla pacjentów', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 10, 
       'helptext': 'j. telekonsultacje z innymi placówkami medycznymi', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
       {'number': 11, 
       'helptext': 'k. system monitorowania dla pacjentów z chorobami przewlekłymi', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},
      {'number': 12, 
       'helptext': 'l. system teleopieki w warunkach domowych', 
       'type': 'select', 
       'options': [
         {'number': 1, 'text': 'tak, w ciągu 12 miesięcy'},
         {'number': 2, 'text': 'tak, w dalszej perspektywie'},
         {'number': 3, 'text': 'nie'}]},   
]} 

exports.steps = [step0, step1, step2, step3, step4, step5, step6, step7]

